services:
  gateway:
    container_name: sandol-gateway
    image: sandol-gateway:${TAG:-latest}
    ports:
      - "8010:80"
    depends_on:
      user-service:
        condition: service_healthy
      meal-service:
        condition: service_healthy
      kakao-bot-service:
        condition: service_healthy
      static-info-service:
        condition: service_healthy
      classroom-timetable-service:
        condition: service_healthy
      notice-notification:
        condition: service_healthy
    env_file:
      - ./.env
    volumes:
      - ./sandol-gateway/gateway:/etc/nginx/conf.d
      - ./sandol-gateway/gateway/lua:/etc/nginx/lua
      - user_static:/usr/share/nginx/static/user
    command: [ "/usr/local/openresty/bin/openresty", "-g", "env SECRET_KEY; daemon off;" ]
    networks:
      - sandol_network
    restart: on-failure
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "7"
    deploy:
      resources:
        limits:
          cpus: '0.8'

  user-service:
    image: sandol-sandol_user_service:${TAG:-latest}
    container_name: sandol_user_service
    env_file:
      - ./.env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - user_static:/app/static
    networks:
      - sandol_network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/user/health" ]
      interval: 60s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: on-failure
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "7"
    deploy:
      resources:
        limits:
          cpus: '0.8'

  meal-service:
    image: sandol-sandol_meal_service:${TAG:-latest}
    container_name: sandol_meal_service
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - ./.env
      - ./sandol_meal_service/.env
    networks:
      - sandol_network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:80/meal/health" ]
      interval: 60s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: on-failure
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "7"
    depends_on:
      meal-service-db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.8'

  meal-service-db:
    container_name: meal-service-db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-meal_service}
    env_file:
      - .env
    volumes:
      - meal_service_db_data:/var/lib/postgresql/data
    networks:
      - sandol_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d meal_service -U postgres" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "7"
    deploy:
      resources:
        limits:
          cpus: '0.8'

  kakao-bot-service:
    image: sandol-sandol_kakao_bot_service:${TAG:-latest}
    container_name: sandol_kakao_bot_service
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - ./.env
      - ./sandol_kakao_bot_service/.env
    networks:
      - sandol_network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:80/kakao-bot/health" ]
      interval: 60s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: on-failure
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "7"
    deploy:
      resources:
        limits:
          cpus: '0.8'

  static-info-service:
    image: sandol-sandol-static-info-service:${TAG:-latest}
    container_name: sandol_static_info_service
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - ./.env
    volumes:
      - ./sandol-static-info-service:/app
    networks:
      - sandol_network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:80/static-info/health" ]
      interval: 60s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: on-failure
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "7"
    deploy:
      resources:
        limits:
          cpus: '0.8'

  classroom-timetable-service:
    image: sandol-sandol_classroom_timetable_service:${TAG:-latest}
    container_name: sandol_classroom_timetable_service
    networks:
      - sandol_network
    healthcheck:
      test: [ "CMD", "wget", "-O", "-", "--tries=1", "http://localhost:80/classroom-timetable/health" ]
      interval: 60s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: on-failure
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "7"
    deploy:
      resources:
        limits:
          cpus: '0.8'

  notice-notification:
    image: sandol-sandol_notice_notification:${TAG:-latest}
    container_name: sandol-notice-notification
    restart: always
    env_file:
      - ./sandol_notice_notification/.env.dev
    networks:
      - sandol_network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/notice-notification/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    depends_on:
      amqp:
        condition: service_healthy
      notice-notification-db:
        condition: service_healthy
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "7"
    deploy:
      resources:
        limits:
          cpus: '0.8'

  notice-notification-db:
    container_name: sandol-notice-notification-db
    image: postgres:15
    restart: always
    env_file:
      - ./sandol_notice_notification/.env.dev
    volumes:
      - notice_notification_db_data:/var/lib/postgresql/data
    networks:
      - sandol_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres -U root" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "7"
    deploy:
      resources:
        limits:
          cpus: '0.5'

  amqp:
    container_name: amqp
    image: rabbitmq:3-management
    networks:
      - sandol_network
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "7"
    deploy:
      resources:
        limits:
          cpus: '0.5'

  loki:
    image: grafana/loki:latest
    container_name: loki
    volumes:
      - ./sandol-log-manager/config/loki/loki-config.yaml:/etc/loki/local-config.yaml
      - ./sandol-log-manager/data:/var/lib/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - sandol_network
    restart: always
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "7"
    deploy:
      resources:
        limits:
          cpus: '0.8'

  prometheus:
    image: prom/prometheus:${PROMETHEUS_VERSION:-v3.3.0}
    container_name: prometheus
    volumes:
      - ./sandol-log-manager/config/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-remote-write-receiver"
    networks:
      - sandol_network
    restart: always
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "7"
    deploy:
      resources:
        limits:
          cpus: '0.5'

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./sandol-log-manager/config/alloy/config.alloy:/etc/alloy/config.alloy
    command: run --log.level=warn /etc/alloy/config.alloy
    depends_on:
      - loki
    networks:
      - sandol_network
    restart: always
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "7"
    deploy:
      resources:
        limits:
          cpus: '0.5'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./sandol-log-manager/config/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - sandol_network
    restart: always
    environment:
      - GF_LOG_LEVEL=warn
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s/grafana
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "7"
    deploy:
      resources:
        limits:
          cpus: '0.8'

volumes:
  user_static: {}
  grafana_data: {}
  meal_service_db_data: {}
  notice_notification_db_data: {}

networks:
  sandol_network:
    driver: bridge
