services:
  sandol:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: sandol_container
    ports:
      - "8080:80"
    volumes:
      - /tmp/sandol/data:/app/crawler/data

  nginx:
    image: nginx:alpine
    container_name: sandol_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - sandol
