name: Deploy to GCP VM

on:
  push:
    branches: [ feature/deploy-test ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: '${{ secrets.GCP_PROJECT_ID }}'

    - name: Copy code to GCP VM
      run: |
        gcloud compute scp --recurse . ${GCP_VM_USER}@${GCP_INSTANCE_NAME}:/home/${GCP_VM_USER}/app --zone ${GCP_ZONE}
      env:
        GCP_INSTANCE_NAME: '${{ secrets.GCP_INSTANCE_NAME }}'
        GCP_VM_USER: '${{ secrets.GCP_VM_USER }}'
        GCP_ZONE: '${{ secrets.GCP_ZONE }}'

    - name: Deploy to GCP VM
      uses: google-github-actions/ssh-compute@v1.1.1
      with:
        instance_name: '${{ secrets.GCP_INSTANCE_NAME }}'
        zone: '${{ secrets.GCP_ZONE }}'
        user: '${{ secrets.GCP_VM_USER }}'
        ssh_private_key: '${{ secrets.GCP_SA_KEY }}'
        command: |
          cd /home/${{ secrets.GCP_VM_USER }}/app
          docker compose -f sandol/docker-compose.yml up -d --build
