name: Deploy sandol server to GCP VM

on:
  workflow_dispatch:  # 수동 배포 트리거

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout with submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
        ref: ${{ github.ref_name }}

    - name: Build all Docker images and save as tar (with debug)
      shell: bash
      run: |
        set -euxo pipefail
        TAG=${{ github.sha }}
        echo "Git SHA TAG: $TAG"
        find . -type f -name 'Dockerfile' | while read dockerfile; do
          echo "========================================"
          echo "Processing Dockerfile: $dockerfile"
          DIR=$(dirname "$dockerfile")
          NAME=$(basename "$DIR")
          IMAGE="sandol-${NAME}:${TAG}"
          TAR_PATH="${DIR}/docker_image_${NAME}_${TAG}.tar"

          echo "Building image: $IMAGE from $DIR"
          docker build --progress=plain -t "$IMAGE" "$DIR"

          echo "Saving image $IMAGE to $TAR_PATH"
          docker save -o "$TAR_PATH" "$IMAGE"

          echo "Verifying tar file:"
          ls -lh "$TAR_PATH"
          echo "========================================"
        done

    - name: Remove .git directory
      run: rm -rf .git
    - name: Validate docker-compose.yml
      run: docker compose config

    - name: Test Docker Compose (local)
      run: |
        docker compose up -d
        sleep 10
        docker compose ps
        docker compose down

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: '${{ secrets.GCP_PROJECT_ID }}'

    - name: Generate SSH key
      run: |
        ssh-keygen -t rsa -b 2048 -f ~/.ssh/id_rsa -q -N ""

    - name: Add SSH key to GCP project metadata
      run: |
        gcloud compute project-info add-metadata --metadata "ssh-keys=${GCP_VM_USER}:$(cat ~/.ssh/id_rsa.pub)"
      env:
        GCP_VM_USER: '${{ secrets.GCP_VM_USER }}'

    - name: Copy entire repo including images to GCP VM
      run: |
        gcloud compute scp --recurse . $GCP_VM_USER@$GCP_INSTANCE_NAME:/home/$GCP_VM_USER/tuk_sandol_team --zone $GCP_ZONE
      env:
        GCP_INSTANCE_NAME: '${{ secrets.GCP_INSTANCE_NAME }}'
        GCP_VM_USER: '${{ secrets.GCP_VM_USER }}'
        GCP_ZONE: '${{ secrets.GCP_ZONE }}'

    - name: Run Docker Compose on GCP VM
      run: |
        gcloud compute ssh $GCP_VM_USER@$GCP_INSTANCE_NAME --zone $GCP_ZONE --command "
          cd /home/$GCP_VM_USER/tuk_sandol_team &&
          find . -type f -name 'docker_image_*.tar' | while read tarfile; do
            echo \"Loading image from \$tarfile\"
            docker load -i \"\$tarfile\"
          done &&
          docker compose up -d
        "
      env:
        GCP_INSTANCE_NAME: '${{ secrets.GCP_INSTANCE_NAME }}'
        GCP_VM_USER: '${{ secrets.GCP_VM_USER }}'
        GCP_ZONE: '${{ secrets.GCP_ZONE }}'
